version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hongsam_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - hongsam_network
    environment:
      - DJANGO_SETTINGS_MODULE=hongsam_BE.settings
    depends_on:
      - mysql
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      - ./ssl:/etc/ssl:ro  
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - django
    networks:
      - hongsam_network

volumes:
  db_data:

networks:
  hongsam_network:
    external: true
