# Generated by Django 3.2.18 on 2024-05-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlaylist',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gameapp.game')),
            ],
            options={
                'db_table': 'Game_Playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=100)),
                ('playlist_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('from_service', models.IntegerField()),
            ],
            options={
                'db_table': 'Playlist',
                'managed': False,
            },
        ),
    ]
