# Generated by Django 3.2.18 on 2024-07-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_gameplaylist_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplaylist',
            options={},
        ),
    ]
